jobs:
  - job: WindowsBuild
    pool: Hosted Windows 2019 with VS 2019
    displayName: Windows Build
    steps:
      - script: dotnet tool restore
        displayName: restoring local tool
      - script: dotnet tool run dotnet-cake build.cake
        displayName: build project
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: PooledStream/bin/Release