jobs:
  - job: WindowsBuild
    pool:
      vmImage: windows-2019
    displayName: Windows Build
    steps:
      - script: dotnet tool restore
        displayName: restoring local tool
      - script: dotnet tool run dotnet-cake build.cake
        displayName: build project
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: PooledStream/bin/Release